[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]

requires-python = ">=3.11.3"

name = "xy_type"

authors = [{ name = "helios", email = "yuyang.0515@qq.com" }]
description = "类型辅助模块"

dynamic = ["version"]

readme = "README.md"

classifiers = ["Programming Language :: Python :: 3"]

dependencies = []

[project.scripts]

[tool.setuptools.packages.find]
where = ["./"]
include = ["xy_type"] # alternatively: `exclude = ["additional*"]`
namespaces = false

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = { file = "VERSION" }
